### ISSUE TITLE
Folders disappeared

### ISSUE THREAD

**Issue by darki73** [GuildDarts/unraid-plugin-docker.folder#1]
For some reason, the folders have disappeared  since yesterday for me.

When i had about 20 containers, everything was fine. Now i am at 26 containers and i cannot see any folders.
I cant create new folders either, buttons are there, but nothing happens on folder creation.

Tried to flush browser cache, tried to restart the server. Nothing happens, there are still no folders i used to have on the Docker tab.

I am running `Unraid 6.8.3` with the plugin of version `2020.07.29`

![screencapture-Docker-2020-08-10-20_26_47 thumb png e4af6dbcdfc561c2f5be40c94f8b5986](https://user-images.githubusercontent.com/1318627/89816674-a7108b00-db4f-11ea-9f9b-aa9bb580a503.png)

Maybe something to do with container name length?

And here is what i see in the Developer Console of Google Chome:
![image png e9859c1694b11565970fa1e81b0b26a2](https://user-images.githubusercontent.com/1318627/89816697-af68c600-db4f-11ea-8fe4-ab7a89c3d7ab.png)

**Comment by GuildDarts** [comment]
Fixed with #2
