### ISSUE TITLE
bug ?

### ISSUE THREAD

**Issue by foXaCe** [GuildDarts/unraid-plugin-docker.folder#3]
hello, very good plugin but after reboot i have a problem.
do not work on dashboard tab

![image](https://user-images.githubusercontent.com/290678/93672202-532b8700-faa9-11ea-85e2-66f68a20fda6.png)

but work on docker tab
![SharedScreenshot](https://user-images.githubusercontent.com/290678/93672239-94239b80-faa9-11ea-8fbd-d4270d6bcca4.jpg)

sorry my english is bad

**Comment by GuildDarts** [comment]
By the looks of things you're on version 6.9.0 so that might have something todo with it.
When you are on the dashboard could you open your browser console and refresh the page. Then check if you get any errors and post them here :)

**Comment by GuildDarts** [comment]
Updated my own system to 6.9.0-beta30 and everything is working fine, so guessing its something else.
Closing for now but if its still an issue just reopen :)
