### ISSUE TITLE
[BUG] Adding a container to two folders causes the folders.json to be broken

### ISSUE THREAD

**Issue by ThaDaVos** [GuildDarts/unraid-plugin-docker.folder#4]
I accidentally added a container to two folders and noticed all my folders to be gone - I checked the folders.json at `/boot/config/plugins/docker.folder` and noticed it was all broken up, no longer any valid json, most folders gone.

**Comment by GuildDarts** [comment]
Sorry that your folders are gone :(
If you delete folders.json it should get recreated and you can remake your folders.
I think i know why it might have happened, will see if i can reproduce and fix :)

**Comment by ThaDaVos** [comment]
Luckily I am a programmer myself - so I manually fixed the .json file

**Comment by GuildDarts** [comment]
Glad that your folders were recoverable :)
Should be fixed with 7a4db82797f615c13ac6ef6341bdfe0ec8a3af31
