### ISSUE TITLE
Folders don't show up properly in safari (or any iOS browser)

### ISSUE THREAD

**Issue by ground7** [GuildDarts/unraid-plugin-docker.folder#5]
In safari/iOS browsers, almost no folders will show up, and if they do, they have a stopped status and don't contain anything.

**Comment by GuildDarts** [comment]
hmmm that's odd. Does it happen on both the dashboard and docker page or just one of them?
Will try and borrow my mom's iphone today and see if i can reproduce it as it looks to be working on my ipad

**Comment by ground7** [comment]
It happens on both the dashboard and docker tab. It happens in safari on my iPad as well, so maybe there's more to it? I'm using svgs.

**Comment by GuildDarts** [comment]
Finally got an apple device to test on. I can't seem to reproduce it, everything is showing up.

My best guess would be that some function is throwing an error and that's causing the issue.
The only issue is it that i dont think you can check for errors on ios without a mac ;(

Could you try and attach your folders either by exporting them or copying folders.json. Maybe it's some setting or combination of settings that safari does not like?

**Comment by GuildDarts** [comment]
After a bit of trial and error found that 'Only animate icon on hover' was causing the issue

I have not fixed the root issue just disabled that feature on mobile since you cant hover there :D 21c052344dc01b19f0449d9dba3f1c3ee8b0f1f4

**Comment by ground7** [comment]
Here's the json.

This problem also happens in my Safari on my Mac VM too.

[Unraid.docker.folder-AllFolders-2021_01_29.json.zip](https://github.com/GuildDarts/unraid-plugin-docker.folder/files/5897334/Unraid.docker.folder-AllFolders-2021_01_29.json.zip)

**Comment by ground7** [comment]
Ah I see you found the issue. That fix seems fine for mobile, but since it happens on MacOS too, maybe there's a better fix?

**Comment by GuildDarts** [comment]
Yeah since i also happens on mac could you check the browser console for any errors?
Will push and update with the fix for mobile now since it also fixes a few other things :)

**Comment by ground7** [comment]
After looking into it a bit, it seems like maybe an issue in general with Safari. Maybe the only fix is to disable the functionality in Safari in general.

**Comment by GuildDarts** [comment]
Yeah i think that is for the best, will do that :)

**Comment by GuildDarts** [comment]
Just updated, i hope that it fixes it :)

**Comment by ground7** [comment]
It's fixed. :)
