### ISSUE TITLE
Can't Create a VM Folder

### ISSUE THREAD

**Issue by ground7** [GuildDarts/unraid-plugin-docker.folder#6]
Recently I tried making a VM folder and I was unable to hit the submit button. The browser threw this error when I tried to:
![image](https://user-images.githubusercontent.com/19885992/106853945-c1976d00-6677-11eb-89a9-3d69914577c1.png)

**Comment by GuildDarts** [comment]
Should be fixed with 0f28b1bcb9bad80e52438343eba7764cb6567ede ^_^

**Comment by ground7** [comment]
Dang you're quick! It's working but I ran into a separate problem.
