### ISSUE TITLE
VM Folder Edit Doesn't Remember Settings

### ISSUE THREAD

**Issue by ground7** [GuildDarts/unraid-plugin-docker.folder#7]
When I click edit folder after making a folder for VMs, my settings are all gone. If I try to add my settings back in this edit view, I get an error like in #6 when I try to submit.

I can delete the folder and start from scratch as a workaround.

**Comment by GuildDarts** [comment]
Should be fixed with: 22a1be2a2d24d6f65114b146c7dd3e5c18828362 :D
I should have tested the commit that broke vm folders 😅 (e40cd4ff343d04ccced145a1032bc92032ac205d)
