### ISSUE TITLE
VM Tab Folder Sorts Alphabetically - Dashboard Sorts by Defined Order

### ISSUE THREAD

**Issue by ground7** [GuildDarts/unraid-plugin-docker.folder#8]
Got one more for you this afternoon. 😄 

I'm able to get the Dashboard view sorted how I want by adding VMs to the folder in a specific order, however, the VM tab will just order them alphabetically within the folder regardless of what I do to try to order them.

**Comment by ground7** [comment]
To add to this, when I attempt to sort my vms in a folder, all of my docker folders will get mixed around.

**Comment by GuildDarts** [comment]
4a15780736f2f47a7e9729f9c92c1f1c11352af5 should fix it :)
Thanks for finding these bugs
