### ISSUE TITLE
I found a security issue

### ISSUE THREAD

**Issue by OmgImAlexis** [GuildDarts/unraid-plugin-docker.folder#9]
Hi,

What's your process for reporting security sensitive issues?

**Comment by GuildDarts** [comment]
Thats a good question umm. I guess you could pm me on the forums or on discord (im in the unraid official) if thats acceptable

**Comment by GuildDarts** [comment]
Fixed in 8423efd3cb3e7be4d9d0710185a3fb72bdca7ef9 & 0b049487a31c8ffe1958989dcfa23ce29f07459f
